/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIClient */

#ifndef _Included_JNIClient
#define _Included_JNIClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIClient
 * Method:    testMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIClient_testMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
