/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIServer */

#ifndef _Included_JNIServer
#define _Included_JNIServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIServer
 * Method:    testMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIServer_testMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
