/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMeth */

#ifndef _Included_NativeMeth
#define _Included_NativeMeth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMeth
 * Method:    singleInputServer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeMeth_singleInputServer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     NativeMeth
 * Method:    singleInputClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeMeth_singleInputClient
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeMeth
 * Method:    multiInputServer
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_NativeMeth_multiInputServer
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     NativeMeth
 * Method:    multiInputClient
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_NativeMeth_multiInputClient
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
